// src/constants/skills/index.tsx

/*
* Adding a Skill Constants
* */

export const ADDOUTPUTITEM = 'ADDOUTPUTITEM';
export const ADDOUTPUTITEM_SUCCESS = 'ADDOUTPUTITEM_SUCCESS';
export const ADDOUTPUTITEM_FAILURE = 'ADDOUTPUTITEM_FAILURE';

export const ADDKNOWLEDGEUNITITEM = 'ADDKNOWLEDGEUNITITEM';
export const ADDKNOWLEDGEUNITITEM_SUCCESS = 'ADDKNOWLEDGEUNITITEM_SUCCESS';
export const ADDKNOWLEDGEUNITITEM_FAILURE = 'ADDKNOWLEDGEUNITITEM_FAILURE';

export const ADDBEHAVIOURITEM = 'ADDBEHAVIOURITEM';
export const ADDBEHAVIOURITEM_SUCCESS = 'ADDBEHAVIOURITEM_SUCCESS';
export const ADDBEHAVIOURITEM_FAILURE = 'ADDBEHAVIOURITEM_FAILURE';

export const ADDBELIEFITEM = 'ADDBELIEFITEM';
export const ADDBELIEFITEM_SUCCESS = 'ADDBELIEFITEM_SUCCESS';
export const ADDBELIEFITEM_FAILURE = 'ADDBELIEFITEM_FAILURE';

export const ADDSKILL = 'ADDSKILL';
export const ADDSKILL_SUCCESS = 'ADDSKILL_SUCCESS';
export const ADDSKILL_FAILURE = 'ADDSKILL_FAILURE';
